### PR TITLE
upgrading to gatsby4

### PR DESCRIPTION
**Pull request by npalm**
Upgrading depdencies to gatsby 4

- upgrade gatsby
- removed now
- added vercel

### CODE REVIEW

**Comment by npalm** [comment]
@JeroenKnoops work in progress, but would be great if you already can do some testing

**Comment by npalm** [comment]
@JeroenKnoops 

Can you verify the upgrade
- test deployment to https://040-code-devnpalm.vercel.app/
- yarn run dev gives one error, but seems working properly
- serving static site locally after yarn run build seems also workking as expected.

**Comment by npalm** [comment]
@JeroenKnoops 

Can you verify the upgrade
- test deployment to https://040-code-devnpalm.vercel.app/
- yarn run dev gives one error, but seems working properly
- serving static site locally after yarn run build seems also workking as expected.

**Comment by npalm** [comment]
error
image

**Review by JeroenKnoops — APPROVED** [review]

**Pull request merged**
